name: DuoScribo
options:
  bundleIdPrefix: ch.yannickmauray
  developmentLanguage: fr
  localizations: [fr, en]
targets:
  DuoScribo:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    bundleId: ch.yannickmauray.DuoScribo
    sources: [Sources]
    settings:
      base:
        INFOPLIST_FILE: Sources/DuoScribo-Info.plist
        GENERATE_INFOPLIST_FILE: NO
        DEVELOPMENT_TEAM: WFMP87LTRX
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_ENTITLEMENTS: Sources/DuoScribo.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLORNAME: SplashColor
        MARKETING_VERSION: 1.1
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: 5.9
    capabilities:
      - icloud:
          services: [CloudKit]
          containerIdentifiers: [iCloud.ch.yannickmauray.DuoScribo]
      - pushNotifications: {}
      - backgroundModes: [remote-notification]
  DuoScriboTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources: [Tests]
    dependencies:
      - target: DuoScribo
    settings:
      base:
        DEVELOPMENT_TEAM: WFMP87LTRX
