name: DuoScribo
options:
  bundleIdPrefix: ch.yannickmauray
  developmentLanguage: fr
  localizations: [fr, en]
targets:
  DuoScribo:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: [Sources]
    info:
      UISupportedInterfaceOrientations:
        - UIInterfaceOrientationPortrait
        - UIInterfaceOrientationPortraitUpsideDown
        - UIInterfaceOrientationLandscapeLeft
        - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIBackgroundModes: ["remote-notification"]
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_ImageName: SplashIcon
        INFOPLIST_KEY_UILaunchScreen_BackgroundColor: SplashColor
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLORNAME: SplashColor
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: 5.9
        DEVELOPMENT_TEAM: WFMP87LTRX
        CODE_SIGN_IDENTITY: "Apple Development"
    entitlements:
      path: Sources/DuoScribo.entitlements
  DuoScriboTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources: [Tests]
    dependencies:
      - target: DuoScribo
    settings:
      base:
        DEVELOPMENT_TEAM: WFMP87LTRX
